Update guide to prefer const-ness instead of not preferring it
Expensify/Style-Guides pull request #11
Opened 2024-01-04 22:19 UTC by bondydaa

Context from: https://expensify.slack.com/archives/C03U45HG0/p1704403572144729

2024-01-05 00:35 UTC, tylerkaraszewski requested changes

2024-01-05 00:35 UTC, tylerkaraszewski commented on cpp.md
> +In most cases, using `const` actually does nothing at all to the final compiled code.
I would just link this article or similar: https://isocpp.org/wiki/faq/const-correctness

2024-01-05 16:33 UTC, bondydaa commented on cpp.md
> +In most cases, using `const` actually does nothing at all to the final compiled code.
updated

2024-01-05 17:05 UTC, puneetlath approved these changes

2024-01-09 00:07 UTC, tylerkaraszewski approved these changes

2024-01-09 00:07 UTC, merged