Add guidance on default params vs function overloading
Expensify/Style-Guides pull request #2
Opened 2021-09-27 19:06 UTC by bondydaa

Adding section about default params vs function overloading as noted in this PR here: https://github.com/Expensify/Auth/pull/5947/#discussion_r716954684

cc @Expensify/engineering thoughts?

2021-09-27 20:00 UTC, johnmlee101 commented on cpp.md
> +const string myMethod (const string& myParam, const string& anotherParam="")
Clarification, usually these optional values are declared in the header files, so having `{ do stuff }` is a bit misleading.

2021-09-27 20:46 UTC, tylerkaraszewski commented on cpp.md
> +const string myMethod (const string& myParam, const string& anotherParam="")
Yes, I think we should clarify that the defaults actually go in the header files, not the cpp files for the style guide.

2021-09-28 15:52 UTC, robertjchen approved these changes

2021-09-28 16:03 UTC, bondydaa commented on cpp.md
> +const string myMethod (const string& myParam, const string& anotherParam="")
updated, you can see it rendered here https://github.com/Expensify/Style-Guides/blob/f1217ffb63a544d87c95eb16f3d7a3c5c406642b/cpp.md

2021-09-28 16:06 UTC, mountiny approved these changes

2021-09-28 16:07 UTC, stitesExpensify approved these changes

2021-09-28 16:09 UTC, cead22 requested changes

2021-09-28 16:09 UTC, cead22 commented on cpp.md
> +const string myMethod (const string& myParam);
Our style guide should follow our style guide :)
- `const string myMethod(const string& myParam);`
- `const string myMethod(const string& myParam, const string& anotherParam);`
- `const string myMethod(const string& myParam, const string& anotherParam = "");`

2021-09-28 16:54 UTC, Julesssss reviewed
NAB: The other code examples in this Readme are formatted differently, perhaps they should be aligned?  (good and bad examples in a single code block)

I'd argue we should leave as is though, as your formatting is clearer to me.

2021-09-28 17:00 UTC, bondydaa commented on cpp.md
> +const string myMethod (const string& myParam);
updated

2021-09-28 17:03 UTC, Julesssss approved these changes

2021-09-28 17:29 UTC, cead22 approved these changes

2021-09-28 17:41 UTC, francoisl approved these changes

2021-09-28 17:58 UTC, Jag96 commented on cpp.md
> +string quotedString(int i) {
Shouldn't the `{` here go on the next line?

2021-09-28 18:01 UTC, bondydaa commented on cpp.md
> +string quotedString(int i) {
updated

2021-09-28 18:03 UTC, Jag96 approved these changes

2021-09-28 18:57 UTC, yuwenmemon approved these changes

2021-09-28 22:55 UTC, tylerkaraszewski approved these changes

2021-09-28 23:47 UTC, coleaeason approved these changes

2021-09-29 05:18 UTC, MariaHCD approved these changes

2021-09-29 11:42 UTC, flodnv approved these changes

2021-09-29 11:43 UTC, merged